//! The async/Tokio shape on top of [`datachannel_facade`].
//!
//! The facade is synchronous and callback-based, because that is what
//! both of its backends are. The rest of Tango is written against an
//! async, channel-based shape — peer-connection events arrive on an
//! `mpsc::Receiver`, data-channel sends and receives are `await`-able.
//! Bridging the two is all this crate does; which backend is underneath
//! is the facade's business, not ours.
//!
//! Callbacks fire wherever the backend fires them — libdatachannel's own
//! network threads natively, the microtask queue in a browser — and get
//! forwarded onto Tokio channels from there.

// Re-export the facade's enums, whose shape/variants we use verbatim.
pub use datachannel_facade::{
    GatheringState, Reliability, SdpType, State as ConnectionState, TransportPolicy,
};

/// Pinned local ICE credentials for [`PeerConnection::set_local_description`].
/// `None` fields are autogenerated as usual; `Some` pins them, so a peer
/// that already knows them can fabricate this side's SDP with no
/// signaling exchange.
///
/// Defined here rather than re-exported so the signature that takes it is
/// the same on every target. Supplying one on wasm fails at runtime with
/// `Unsupported`: web content cannot choose its own ICE credentials, so a
/// transport built on this is native-only. (The facade states that at
/// *compile* time; this crate trades that for a stable signature, since
/// the one caller that pins credentials is already native-only.)
#[derive(Default, Debug, Clone)]
pub struct LocalDescriptionInit {
    pub ice_ufrag: Option<String>,
    pub ice_pwd: Option<String>,
}

/// An ICE candidate string emitted by the local agent. Tango does non-trickle
/// ICE (it waits for gathering to complete and ships the full SDP), so nothing
/// consumes these today, but they're surfaced for API completeness.
#[derive(Debug, Clone)]
pub struct IceCandidate {
    pub candidate: String,
}

/// A full SDP session description. `sdp` is just the raw SDP text; the
/// backend parses and serializes it.
#[derive(Debug, Clone)]
pub struct SessionDescription {
    pub sdp_type: SdpType,
    pub sdp: String,
}

/// Peer connection configuration. A thin stand-in for the old `RtcConfig`,
/// carrying only what Tango sets.
#[derive(Debug, Clone, Default)]
pub struct RtcConfig {
    pub ice_servers: Vec<String>,
    pub ice_transport_policy: TransportPolicy,
    /// Skip the DTLS fingerprint check. Required by the signaling-free
    /// direct transport, whose fabricated remote SDP carries a dummy
    /// (non-matching) fingerprint. Native-only.
    pub disable_fingerprint_verification: bool,
    /// Don't auto-generate an offer when a data channel is created. The
    /// signaling-free direct transport needs this so its own
    /// pinned-credential `set_local_description` is what runs, rather
    /// than an auto offer with random creds. Native-only.
    pub disable_auto_negotiation: bool,
    /// Pin the local UDP port range, `(begin, end)`. The signaling-free
    /// host sets `(port, port)` so the dialing peer knows where to reach
    /// it. `None` lets the backend pick. Native-only.
    pub port_range: Option<(u16, u16)>,
}

impl RtcConfig {
    pub fn new<S: AsRef<str>>(ice_servers: &[S]) -> Self {
        Self {
            ice_servers: ice_servers.iter().map(|s| s.as_ref().to_owned()).collect(),
            ice_transport_policy: TransportPolicy::All,
            ..Default::default()
        }
    }
}

/// Builder for data-channel options, matching the old fluent API
/// (`DataChannelInit::default().reliability(..).negotiated().manual_stream().stream(0)`).
#[derive(Clone, Default)]
pub struct DataChannelInit(datachannel_facade::DataChannelOptions);

impl DataChannelInit {
    pub fn reliability(mut self, reliability: Reliability) -> Self {
        self.0.reliability = reliability;
        self
    }

    pub fn negotiated(mut self) -> Self {
        self.0.negotiated = true;
        self
    }

    /// Use a caller-assigned stream id. A manual stream is simply
    /// expressed as `stream = Some(..)`, so this is a no-op kept for API
    /// compatibility — call [`DataChannelInit::stream`] to set the id.
    pub fn manual_stream(self) -> Self {
        self
    }

    pub fn stream(mut self, stream: u16) -> Self {
        self.0.stream = Some(stream);
        self
    }

    pub fn protocol(mut self, protocol: String) -> Self {
        self.0.protocol = protocol;
        self
    }
}

/// Events forwarded off the backend's callbacks onto the
/// peer-connection's event channel.
#[derive(Debug)]
pub enum PeerConnectionEvent {
    SessionDescription(SessionDescription),
    IceCandidate(IceCandidate),
    ConnectionStateChange(ConnectionState),
    GatheringStateChange(GatheringState),
}

/// The facade's error carries a backend-specific payload, and callers
/// here only ever want an `io::Error`, so flatten it through Display
/// rather than matching variants that differ per backend.
fn error_to_io(err: datachannel_facade::Error) -> std::io::Error {
    std::io::Error::other(err.to_string())
}

/// The stream of everything a [`PeerConnection`] reports: its local
/// description, its ICE candidates, and its state changes.
pub type EventReceiver = futures::channel::mpsc::UnboundedReceiver<PeerConnectionEvent>;

pub struct PeerConnection {
    inner: datachannel_facade::PeerConnection,
    data_channel_rx: futures::channel::mpsc::UnboundedReceiver<DataChannel>,
}

impl PeerConnection {
    pub fn new(
        config: RtcConfig,
    ) -> Result<(Self, EventReceiver), std::io::Error> {
        // Unbounded, because every producer here is a callback that cannot
        // wait: libdatachannel fires them from its network threads (and, on
        // teardown, from a destructor that may already be on a runtime
        // thread), and a browser fires them on the one thread it has, where
        // blocking is fatal rather than merely rude. The queues are shallow
        // in practice — an ICE gathering burst, then nothing.
        let (event_tx, event_rx) = futures::channel::mpsc::unbounded();
        let (data_channel_tx, data_channel_rx) = futures::channel::mpsc::unbounded();

        let mut facade_config = datachannel_facade::Configuration::new();
        facade_config.ice_servers = config.ice_servers;
        facade_config.ice_transport_policy = config.ice_transport_policy;

        // The rest of RtcConfig is the signaling-free direct transport's
        // needs, none of which a browser can express.
        #[cfg(not(target_arch = "wasm32"))]
        {
            use datachannel_facade::platform::native::ConfigurationExt as _;
            let (begin, end) = config.port_range.unwrap_or((0, 0));
            facade_config.set_bind(None, begin, end);
            facade_config.set_disable_auto_negotiation(config.disable_auto_negotiation);
            facade_config
                .set_disable_fingerprint_verification(config.disable_fingerprint_verification);
        }
        // `disable_auto_negotiation` isn't in this list: a browser only
        // ever negotiates when told to, so asking for manual negotiation
        // is asking for what it already does. Asking to *keep* automatic
        // negotiation is the unrepresentable one.
        #[cfg(target_arch = "wasm32")]
        if config.disable_fingerprint_verification
            || !config.disable_auto_negotiation
            || config.port_range.is_some()
        {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Unsupported,
                "pinned ports, automatic negotiation and disabled fingerprint verification are native-only",
            ));
        }

        let mut inner =
            datachannel_facade::PeerConnection::new(facade_config).map_err(error_to_io)?;

        inner.set_on_local_description(Some({
            let event_tx = event_tx.clone();
            move |sdp: &str, type_: SdpType| {
                let _ = event_tx.unbounded_send(PeerConnectionEvent::SessionDescription(
                    SessionDescription {
                        sdp_type: type_,
                        sdp: sdp.to_owned(),
                    },
                ));
            }
        }));

        inner.set_on_local_candidate(Some({
            let event_tx = event_tx.clone();
            move |cand: &str| {
                let _ = event_tx.unbounded_send(PeerConnectionEvent::IceCandidate(IceCandidate {
                    candidate: cand.to_owned(),
                }));
            }
        }));

        inner.set_on_state_change(Some({
            let event_tx = event_tx.clone();
            move |state: ConnectionState| {
                let _ = event_tx.unbounded_send(PeerConnectionEvent::ConnectionStateChange(state));
            }
        }));

        inner.set_on_gathering_state_change(Some({
            let event_tx = event_tx.clone();
            move |state: GatheringState| {
                let _ = event_tx.unbounded_send(PeerConnectionEvent::GatheringStateChange(state));
            }
        }));

        inner.set_on_data_channel(Some({
            let data_channel_tx = data_channel_tx.clone();
            move |dc: datachannel_facade::DataChannel| {
                let _ = data_channel_tx.unbounded_send(DataChannel::wrap(dc));
            }
        }));

        Ok((
            PeerConnection {
                inner,
                data_channel_rx,
            },
            event_rx,
        ))
    }

    pub fn create_data_channel(
        &mut self,
        label: &str,
        dc_init: DataChannelInit,
    ) -> Result<DataChannel, std::io::Error> {
        let dc = self
            .inner
            .create_data_channel(label, dc_init.0)
            .map_err(error_to_io)?;
        Ok(DataChannel::wrap(dc))
    }

    pub async fn accept(&mut self) -> Option<DataChannel> {
        futures::StreamExt::next(&mut self.data_channel_rx).await
    }

    /// Set the local description, optionally with pinned ICE credentials.
    ///
    /// The SDP is not returned: it arrives as a
    /// [`PeerConnectionEvent::SessionDescription`] on the event channel,
    /// on both targets.
    pub fn set_local_description(
        &mut self,
        sdp_type: SdpType,
        init: Option<&LocalDescriptionInit>,
    ) -> Result<(), std::io::Error> {
        match init {
            None => self
                .inner
                .set_local_description(Some(sdp_type))
                .map_err(error_to_io),
            #[cfg(not(target_arch = "wasm32"))]
            Some(init) => {
                use datachannel_facade::platform::native::PeerConnectionExt as _;
                self.inner
                    .set_local_description_ex(
                        Some(sdp_type),
                        Some(
                            &datachannel_facade::platform::native::LocalDescriptionInit {
                                ice_ufrag: init.ice_ufrag.clone(),
                                ice_pwd: init.ice_pwd.clone(),
                            },
                        ),
                    )
                    .map_err(error_to_io)
            }
            #[cfg(target_arch = "wasm32")]
            Some(_) => Err(std::io::Error::new(
                std::io::ErrorKind::Unsupported,
                "pinned ICE credentials are native-only",
            )),
        }
    }

    pub fn set_remote_description(
        &mut self,
        sess_desc: SessionDescription,
    ) -> Result<(), std::io::Error> {
        self.inner
            .set_remote_description(&datachannel_facade::Description {
                type_: sess_desc.sdp_type,
                sdp: sess_desc.sdp,
            })
            .map_err(error_to_io)
    }

    pub fn local_description(&self) -> Option<SessionDescription> {
        self.inner
            .local_description()
            .ok()
            .map(|d| SessionDescription {
                sdp_type: d.type_,
                sdp: d.sdp,
            })
    }

    pub fn remote_description(&self) -> Option<SessionDescription> {
        self.inner
            .remote_description()
            .ok()
            .map(|d| SessionDescription {
                sdp_type: d.type_,
                sdp: d.sdp,
            })
    }

    pub fn add_remote_candidate(&mut self, cand: IceCandidate) -> Result<(), std::io::Error> {
        self.inner
            .add_remote_candidate(&cand.candidate)
            .map_err(error_to_io)
    }

    /// The selected ICE candidate pair as raw candidate strings,
    /// `(local, remote)` — e.g. for telling a relayed (TURN)
    /// connection from a direct one (`typ relay`). Errors until
    /// the agent has picked a pair.
    pub fn selected_candidate_pair(&self) -> Result<(String, String), std::io::Error> {
        #[cfg(not(target_arch = "wasm32"))]
        {
            use datachannel_facade::platform::native::PeerConnectionExt as _;
            self.inner.selected_candidate_pair().map_err(error_to_io)
        }
        // A browser answers this only through async `getStats()`. Callers
        // treat the error as "couldn't tell", which is the truth here.
        #[cfg(target_arch = "wasm32")]
        Err(std::io::Error::new(
            std::io::ErrorKind::Unsupported,
            "the selected candidate pair is not available synchronously on web",
        ))
    }
}

/// The lifecycle of a data channel as observed by the send side.
#[derive(Debug, Clone)]
enum DataChannelStatus {
    Pending,
    Open,
    Closed,
    Error(String),
}

/// A data channel's state, shared between the callbacks that set it and
/// the sends that wait on it.
///
/// Two halves, because they answer different questions: `settled` fires
/// once, the first time the channel stops being `Pending`, and is what a
/// send waits on; `current` is the latest value, which can move on again
/// (an open channel closes) and is what the send then reads. A
/// `watch`-style channel would fold them into one at the cost of a
/// runtime-flavoured dependency this crate no longer needs.
#[derive(Clone)]
struct Status {
    settled: futures::future::Shared<futures::channel::oneshot::Receiver<()>>,
    /// Taken by whichever callback settles it first.
    settle: std::sync::Arc<std::sync::Mutex<Option<futures::channel::oneshot::Sender<()>>>>,
    current: std::sync::Arc<std::sync::Mutex<DataChannelStatus>>,
}

impl Status {
    fn new() -> Self {
        let (settle, settled) = futures::channel::oneshot::channel();
        Self {
            settled: futures::FutureExt::shared(settled),
            settle: std::sync::Arc::new(std::sync::Mutex::new(Some(settle))),
            current: std::sync::Arc::new(std::sync::Mutex::new(DataChannelStatus::Pending)),
        }
    }

    fn set(&self, status: DataChannelStatus) {
        *self.current.lock().unwrap() = status;
        if let Some(settle) = self.settle.lock().unwrap().take() {
            let _ = settle.send(());
        }
    }

    /// The state once the channel has stopped being `Pending`. A dropped
    /// latch means the channel went away before it ever opened.
    async fn settled(&self) -> DataChannelStatus {
        if self.settled.clone().await.is_err() {
            return DataChannelStatus::Closed;
        }
        self.current.lock().unwrap().clone()
    }
}

pub struct DataChannel {
    sender: DataChannelSender,
    receiver: DataChannelReceiver,
}

impl DataChannel {
    /// Attach our Tokio-channel callbacks to a backend data channel and
    /// split it into a sender/receiver pair. Shared by `create_data_channel`
    /// (local) and the `on_data_channel` callback (remote-opened).
    fn wrap(mut inner: datachannel_facade::DataChannel) -> Self {
        let status = Status::new();

        // Unbounded for the same reason the peer connection's queues are:
        // `on_message` is a callback with nowhere to wait. Wrapped in an
        // Option so `on_closed` can drop the sender and signal EOF to the
        // receiver even while the channel object is still alive.
        let (message_tx, message_rx) = futures::channel::mpsc::unbounded::<Vec<u8>>();
        let message_tx = std::sync::Arc::new(std::sync::Mutex::new(Some(message_tx)));

        inner.set_on_open(Some({
            let status = status.clone();
            move || status.set(DataChannelStatus::Open)
        }));

        inner.set_on_error(Some({
            let status = status.clone();
            move |err: &str| status.set(DataChannelStatus::Error(err.to_owned()))
        }));

        inner.set_on_closed(Some({
            let status = status.clone();
            let message_tx = message_tx.clone();
            move || {
                status.set(DataChannelStatus::Closed);
                // Drop the sender so an idle `receive()` observes EOF.
                *message_tx.lock().unwrap() = None;
            }
        }));

        inner.set_on_message(Some({
            let message_tx = message_tx.clone();
            move |msg: &[u8]| {
                if let Some(tx) = message_tx.lock().unwrap().as_ref() {
                    let _ = tx.unbounded_send(msg.to_vec());
                }
            }
        }));

        DataChannel {
            sender: DataChannelSender { inner, status },
            receiver: DataChannelReceiver { message_rx },
        }
    }

    pub async fn send(&mut self, msg: &[u8]) -> Result<(), std::io::Error> {
        self.sender.send(msg).await
    }

    pub async fn receive(&mut self) -> Option<Vec<u8>> {
        self.receiver.receive().await
    }

    pub fn split(self) -> (DataChannelSender, DataChannelReceiver) {
        (self.sender, self.receiver)
    }
}

pub struct DataChannelSender {
    inner: datachannel_facade::DataChannel,
    status: Status,
}

impl DataChannelSender {
    pub async fn send(&mut self, msg: &[u8]) -> Result<(), std::io::Error> {
        // Wait out the first send until the channel leaves `Pending` (opens
        // or dies); once it has, this returns immediately on every later send.
        match self.status.settled().await {
            DataChannelStatus::Open => {}
            DataChannelStatus::Error(err) => return Err(std::io::Error::other(err)),
            DataChannelStatus::Closed => {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::NotConnected,
                    "not connected",
                ))
            }
            DataChannelStatus::Pending => unreachable!("`settled` guarantees we left Pending"),
        }

        self.inner.send(msg).map_err(error_to_io)
    }

    pub fn unsplit(self, receiver: DataChannelReceiver) -> DataChannel {
        DataChannel {
            sender: self,
            receiver,
        }
    }
}

pub struct DataChannelReceiver {
    message_rx: futures::channel::mpsc::UnboundedReceiver<Vec<u8>>,
}

impl DataChannelReceiver {
    pub async fn receive(&mut self) -> Option<Vec<u8>> {
        futures::StreamExt::next(&mut self.message_rx).await
    }

    pub fn unsplit(self, tx: DataChannelSender) -> DataChannel {
        tx.unsplit(self)
    }
}
